# Generated by Django 3.0.2 on 2020-02-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Winemaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=400)),
                ('quantity', models.IntegerField(default=0)),
                ('consumed', models.IntegerField(default=0)),
                ('comments', models.TextField(max_length=2000)),
                ('score', models.FloatField()),
                ('price', models.FloatField()),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine.Nation')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine.Variety')),
                ('winemaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine.Winemaker')),
            ],
        ),
    ]
