# Generated by Django 3.0.2 on 2020-03-11 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='last_drank_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wine',
            name='last_stock_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
