# Generated by Django 3.0.2 on 2020-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20200311_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='last_drank_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='last_stock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
