# Generated by Django 3.0.2 on 2020-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20200311_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='comments',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='wine',
            name='score',
            field=models.FloatField(blank=True),
        ),
    ]
